# Generated by Django 4.2 on 2023-04-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
